config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  devise_for :users
  get 'welcome/index'
  
  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update]
  
  def index
    @entries = Entry.all
  end
  def show
  end
  def new
      @entry = Entry.new
  end
  def create
      @entry = Entry.create(entry_params)
      redirect_to @entry
  end
  def edit
      
  end
  def update
     
      
    if @entry.update(entry_params)
      redirect_to @entry
    else
        render :edit
    end
     
  end
  private
  
  def entry_params
    params.require(:entry).permit(:title, :contents)
  end
  
  def set_entry
    @entry = Entry.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>

app/views/entries/edit.html.erb
<%= render partial: "form"%>

app/views/entries/index.html.erb
<h1>Beata</h1>
<h2>Programuje ;)</h2>
<h1>My Rails Girls Diary</h1>
  <ul>
<% for entry in @entries %>
  <li>
      <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
      <h2><%= link_to(entry.title, entry_url(entry)) %></h2>
      <p><%= entry.date %></p>
      <p><%= entry.contents %></p>
      <p><%= link_to("Edit this entry", edit_entry_path(entry)) %></p>
  </li>
<% end %>
  </ul>

app/views/entries/new.html.erb
<%= render partial: "form"%>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= link_to("Back to all entries", entries_path) %></h2>
<h1><%= @entry.title%></h1>
<p><%= @entry.contents%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RGB 2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
  <%= current_user.email %>
  <%= button_to("Sign out", destroy_user_session_path(), method: :delete) %>
  <% else %>
  <%=  link_to("Sign in",  new_user_session_path()) %>
  <% end %>
  
<%= yield %>

</body>
</html>